<?php

namespace App\Database\Seeds;

class PaymentsSeeder extends \CodeIgniter\Database\Seeder
{
    public function run()
    {
        $datas = [
            [
                'type'          => 'bank_transfer',
                'type_name'     => 'Bank Transfer',
                'code'          => 'bca',
                'name'          => 'BCA',
                'service'       => '',
                'icon'          => 'bca_logo.png',
                'description'   => 'Pay from BCA ATMs or internet banking',
                'note'          => 'Bayar pesanan ke Virtual Account di atas sebelum membuat pesanan kembali dengan Virtual Account. \n\n Hanya menerima dari Bank BCA. \n\n\n Dicek dalam 10 menit setelah pembayaran berhasil',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'bank_transfer',
                'type_name'     => 'Bank Transfer',
                'code'          => 'bni',
                'name'          => 'BNI',
                'service'       => '',
                'icon'          => 'bni_logo.png',
                'description'   => 'Pay from BNI ATMs or internet banking',
                'note'          => 'Bayar pesanan ke Virtual Account di atas sebelum membuat pesanan kembali dengan Virtual Account. \n\n Hanya menerima dari Bank BNI. \n\n\n Dicek dalam 10 menit setelah pembayaran berhasil',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'bank_transfer',
                'type_name'     => 'Bank Transfer',
                'code'          => 'bri',
                'name'          => 'BRI',
                'service'       => '',
                'icon'          => 'bri_logo.png',
                'description'   => 'Pay from BRI ATMs or internet banking',
                'note'          => 'Bayar pesanan ke Virtual Account di atas sebelum membuat pesanan kembali dengan Virtual Account. \n\n Hanya menerima dari Bank BRI. \n\n\n Dicek dalam 10 menit setelah pembayaran berhasil',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'bank_transfer',
                'type_name'     => 'Bank Transfer',
                'code'          => 'echannel',
                'service'       => '',
                'name'          => 'Mandiri Bill',
                'icon'          => 'mandiri_logo.png',
                'description'   => 'Pay from Mandiri ATMs or internet banking',
                'note'          => 'Bayar pesanan ke Virtual Account di atas sebelum membuat pesanan kembali dengan Virtual Account. \n\n Hanya menerima dari Bank Mandiri Bill. \n\n\n Dicek dalam 10 menit setelah pembayaran berhasil',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'bank_transfer',
                'type_name'     => 'Bank Transfer',
                'code'          => 'permata',
                'service'       => '',
                'name'          => 'Permata Bank',
                'icon'          => 'permata_bank_logo.png',
                'description'   => 'Pay from Permata ATMs or internet banking',
                'note'          => 'Bayar pesanan ke Virtual Account di atas sebelum membuat pesanan kembali dengan Virtual Account. \n\n Hanya menerima dari Permata Bank. \n\n\n Dicek dalam 10 menit setelah pembayaran berhasil',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'bank_transfer',
                'type_name'     => 'Bank Transfer',
                'code'          => 'bri',
                'service'       => '',
                'name'          => 'Other Bank',
                'icon'          => 'other_bank.png',
                'description'   => 'Pay from Other Bank ATMs',
                'note'          => '',
                'is_activated'    => true,
                'fee'           => 1000,
            ],
            [
                'type'          => 'card',
                'type_name'     => 'Card',
                'code'          => 'credit_card',
                'service'       => '',
                'name'          => 'Credit Card',
                'icon'          => 'credit_card_logo.png',
                'description'   => 'Pay with Visa or MasterCard',
                'note'          => '',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'e-wallet',
                'type_name'     => 'E-wallet',
                'code'          => 'gopay',
                'name'          => 'Gopay',
                'service'       => '',
                'icon'          => 'gopay_logo.png',
                'description'   => 'Pay with your GoPay wallet',
                'note'          => '',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'e-wallet',
                'type_name'     => 'E-wallet',
                'code'          => 'qris',
                'name'          => 'QRIS',
                'service'       => '',
                'icon'          => 'qris_logo.png',
                'description'   => 'Pay with your QRIS',
                'note'          => 'Untuk melakukan pembayara silahkan scan QR Code atau klik Bayar sekarang',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'debit',
                'type_name'     => 'Debit',
                'code'          => 'bca_klikpay',
                'name'          => 'BCA KlikPay',
                'service'       => '',
                'icon'          => 'bca_klikpay_logo.png',
                'description'   => 'Pay with BCA KlikPay',
                'note'          => '',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'debit',
                'type_name'     => 'Debit',
                'code'          => 'cimb_clicks',
                'name'          => 'CIMB Clicks',
                'service'       => '',
                'icon'          => 'cimb_clicks_logo.png',
                'description'   => 'Pay with CIMB Clicks',
                'note'          => '',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'debit',
                'type_name'     => 'Debit',
                'code'          => 'danamon_online',
                'name'          => 'Danamon Online',
                'service'       => '',
                'icon'          => 'danamon_logo.png',
                'description'   => 'Pay with your Danamon Online account',
                'note'          => '',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'debit',
                'type_name'     => 'debit',
                'code'          => 'bri_epay',
                'name'          => 'ePay BRI',
                'service'       => '',
                'icon'          => 'epay_bri_logo.png',
                'description'   => 'Pay with ePay BRI',
                'note'          => '',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'cstore',
                'type_name'     => 'Convenience Store',
                'code'          => 'alfamart',
                'name'          => 'Alfa Group',
                'service'       => '',
                'icon'          => 'alfamart_logo.png',
                'description'   => 'Pay from Alfa Group',
                'note'          => '',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'cstore',
                'type_name'     => 'Convenience Store',
                'code'          => 'indomaret',
                'name'          => 'Indomaret',
                'service'       => '',
                'icon'          => 'indomaret_logo.png',
                'description'   => 'Pay from Indomaret',
                'note'          => '',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'cardless_credit',
                'type_name'     => 'Cardless Credit',
                'code'          => 'akulaku',
                'name'          => 'Akulaku',
                'service'       => '',
                'icon'          => 'akulaku_logo.png',
                'description'   => 'Pay with your Akulaku account',
                'note'          => '',
                'is_activated'    => true,
                'fee'           => 1000,
            ], [
                'type'          => 'cod',
                'type_name'     => 'COD',
                'code'          => 'cod',
                'service'       => '',
                'name'          => 'COD (Cash on Delivery)',
                'icon'          => 'cod_logo.png',
                'description'   => 'Cash on Delivery',
                'note'          => '',
                'is_activated'    => true,
                'fee'           => 1000,
            ]
        ];
        $this->db->table('payments')->insertBatch($datas);
    }
}
